export const CREATE_COURSE_ERROR = 'CREATE_COURSE_ERROR';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const GET_COURSES_ERROR = 'GET_COURSES_ERROR';
export const GET_COURSES_STARTED = 'GET_COURSES_STARTED';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const SAVE_COURSE_STARTED = 'SAVE_COURSE_STARTED';
export const UPDATE_COURSE_ERROR = 'UPDATE_COURSE_ERROR';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
